controllers/usuario_controller.py
# Ruta	Qué hace	Método
# /usuarios/	Lista todos los usuarios	GET
# /usuarios/create	Muestra formulario o guarda nuevo usuario	GET / POST
# /usuarios/edit/<id>	Muestra o actualiza un usuario	GET / POST
# /usuarios/delete/<id>	Elimina un usuario	GET

# request: Permite acceder a datos enviados por formularios (como POST).
# redirect: Redirige a otra página.
# url_for: Genera URLs con nombre de funciones.
# Blueprint: Agrupa rutas en un módulo (útil para organizar código grande).
from flask import request, redirect, url_for, Blueprint
# Usuario: Modelo del usuario, conectado con la base de datos.
# usuario_view: Contiene las funciones para renderizar las plantillas HTML (list, create, edit).
from models.usuario_model import Usuario
from views import usuario_view
#Crea blueprint. Esto define un módulo de rutas. Todas las rutas aquí van a empezar con /usuarios.
usuario_bp = Blueprint('usuario',__name__,url_prefix="/usuarios")
# Ruta /usuarios/ – Ver todos los usuarios
# Se llama cuando entras a /usuarios/
# Recupera todos los usuarios con Usuario.get_all()
# Muestra la plantilla usando usuario_view.list(...)
@usuario_bp.route("/")
def index():
    #Recupera todos los registros de usuarios
    usuarios = Usuario.get_all()
    return usuario_view.list(usuarios)
#  Ruta /usuarios/create – Crear nuevo usuario
# Si es GET: Muestra el formulario de creación (create.html)
# Si es POST: Recoge los datos del formulario, crea un usuario y lo guarda.
# Luego redirige a la lista de usuarios (usuario.index)
@usuario_bp.route("/create", methods=['GET','POST'])
def create():
    if request.method == 'POST':
        nombre = request.form['nombre']
        username = request.form['username']
        password = request.form['password']
        rol = request.form['rol']

        usuario = Usuario(nombre,username,password,rol)
        usuario.save()
        return redirect(url_for('usuario.index'))
    return usuario_view.create()
# Ruta /usuarios/edit/<id> – Editar un usuario
# GET: Muestra el formulario con los datos del usuario actual.
# POST: Actualiza los datos con los del formulario.
# Redirige a la lista de usuarios después de guardar.
@usuario_bp.route("/edit/<int:id>", methods=['GET','POST'])
def edit(id):
    usuario = Usuario.get_by_id(id)
    if request.method == 'POST':
        nombre = request.form['nombre']
        username = request.form['username']
        password = request.form['password']
        rol = request.form['rol']
        #Actualizar
        usuario.update(nombre=nombre,username=username,password=password,rol=rol)
        return redirect(url_for('usuario.index'))
    return usuario_view.edit(usuario)
#  Ruta /usuarios/delete/<id> – Eliminar usuario
# Busca al usuario por su ID.
# Lo elimina de la base de datos.
# Redirige a la lista de usuarios.
@usuario_bp.route("/delete/<int:id>")
def delete(id):
    usuario = Usuario.get_by_id(id)
    usuario.delete()
    return redirect(url_for('usuario.index'))

views/usuario_view.py
from flask import render_template
#Muestra todos los usuarios
# Muestra la página usuarios/index.html.
# Le pasa una variable llamada usuarios (probablemente una lista de usuarios desde la base de datos).
# Esa variable se puede usar en el HTML con Jinja, por ejemplo:
# {% for u in usuarios %}
#   <p>{{ u.nombre }}</p>
# {% endfor %}
def list(usuarios):
    return render_template('usuario/index.html', usuarios = usuarios)
#Muestra formulario vacio para crear usuario
# Muestra la plantilla usuario/create.html.
# Generalmente contiene un formulario para crear un nuevo usuario.
# No recibe datos porque solo muestra el formulario vacío.
def create():
    return render_template('usuario/create.html')
#Muestra formulario lleno para editar usuario
# Muestra la plantilla usuario/edit.html.
# Le pasa la variable usuario, que contiene los datos del usuario a editar.
# En la plantilla puedes rellenar un formulario con esos datos, como:
# <input type="text" name="nombre" value="{{ usuario.nombre }}">
def edit(usuario):
    return render_template('usuario/edit.html', usuario = usuario)

templates/usuario/create.html
{% extends 'base.html' %}

{% block title %} USUARIOS | CREATE {% endblock %}

{% block content %}

<h1>Registro de usuario</h1>

<form action="{{ url_for('usuario.create') }}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Usuario</label>
        <input type="text" class="form-control" name="username" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" class="form-control" name="password" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Rol</label>
        <select name="rol" class="form-select" required>
            <option value="admin">Admin</option>
            <option value="cajero">Cajero</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Registrar usuario</button>
</form>

{% endblock %}

templates/usuario/edit.html
{% extends 'base.html' %}

{% block title %} USUARIOS | EDIT {% endblock %}

{% block content %}

<h1>Actualizacion de usuario</h1>

<form action="{{ url_for('usuario.edit',id=usuario.id) }}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" value="{{ usuario.nombre }}">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Usuario</label>
        <input type="text" class="form-control" name="username" value="{{ usuario.username }}">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" class="form-control" name="password">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Rol</label>
        <select name="rol" class="form-select" required>
            <option value="admin"{% if usuario.rol=='admin' %}selected{% endif %}>Admin</option>
            <option value="cajero"{% if usuario.rol=='cajero' %}selected{% endif %}>Cajero</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Actualizar usuario</button>
</form>

{% endblock %}

templates/usuario/index.html
{% extends 'base.html' %}

{% block title %} USUARIOS {% endblock %}

{% block content %}

<h1>Lista de usuarios</h1>

<a href="{{ url_for('usuario.create') }}" class="btn btn-success mb-3">Nuevo</a>

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Username</th>
        <th>Rol</th>
        <th></th>
        <th></th>
    </tr>
    {% for item in usuarios %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.nombre}}</td>
        <td>{{item.username}}</td>
        <td>{{item.rol}}</td>
        <td>
            <a href="{{ url_for('usuario.edit',id=item.id) }}" class="btn btn-warning">Editar</a>
        </td>
        <td>
            <a href="{{ url_for('usuario.delete',id=item.id) }}" class="btn btn-danger">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}